INSERT INTO building (name) VALUES
('Hardin Hall'),
('Academic Success Center'),
('Barre Hall'),
('Biological Sciences Field Station'),
('Biosystems Research Complex'),
('Brackett Hall'),
('Brooks Center for the Performing Arts'),
('Cook Engineering Laboratory'),
('Cooper Library'),
('Daniel Hall'),
('Earle Hall'),
('Edwards Hall'),
('Endocrine Physiology Laboratory'),
('Fluor Daniel Engineering'),
('Innovation Building'),
('Freeman Hall'),
('Godfrey Hall'),
('Godley-Snell Research Center'),
('Greenhouse Complex')
