'Hardin Hall'  
'Academic Success Center'
'Barre Hall'
'Biological Sciences Field Station'
'Biosystems Research Complex'
'Brackett Hall'
'Brooks Center for the Performing Arts'
'Cook Engineering Laboratory'
'Cooper Library'
'Daniel Hall'
'Earle Hall'
'Edwards Hall'
'Endocrine Physiology Laboratory'
'Fluor Daniel Engineering'
'Innovation Building'
'Freeman Hall'
'Godfrey Hall'
'Godley-Snell Research Center'
'Greenhouse Complex'
'Hardin Hall'
'Holtzendorff Hall'
'Houston Center'
'Hunter Chemistry Laboratory'
'Jordan Hall'
'Kinard Laboratory of Physics'
'Lee Hall'
'Lehotsky Hall'
'Life Sciences Building'
'Long Hall'
'Lowry Hall'
'Martin Hall'
'McAdams Hall'
'Newman Hall'
'Olin Hall'
'Poole Agricultural Center'
'Rhodes Annex'
'Rhodes Engineering Research Center'
'Riggs Hall'
'Sirrine Hall'
'Smith Building for Sonoco Institute of Packaging Design and Graphics'
'Strode Tower'
'Strom Thurmond Institute'
'Tillman Hall'
'Vickery Hall'
'Watt Family Innovation Center'
'Administrative Services Building'
'Alumni Center'
'Brackett Hall'
'Central Energy Facility'
'Clemson University Foundation/Shirley Center for Philanthropy'
'Dillard Building'
'Fire Station'
'Gentry Hall'
'Harcombe Hall'
'Kite Hill Recycling Center'
'Littlejohn House'
'Maintenance Stores'
'Mell Hall'
'Motor Pool'
'National Dropout Prevention Center'
'Parking and Transportation Services'
'Police Department'
'President’s Home'
'Sikes Hall'
'Trustee House'
'University Facilities Offices'
'Clemson Memorial Stadium and Frank Howard Field'
'Football Practice Facility'
'IPTAY/Ticket Office'
'Jervey Athletic Center'
'Littlejohn Coliseum'
'McFadden Building'
'Riggs Field (Soccer Stadium)'
'Sloan Tennis Center'
'Tiger Field (Kingsmore Baseball Stadium)'
'Cooper Library (Cooper Café)'
'Fernow Street Café (Chick-Fil-A®)'
'Hendrix Student Center (Hendrix Food Court, Einstein Bros® and P.O.D. Market)'
'Madren Center (Solé on the Green Restaurant)'
'Schilletter Dining Hall (Wendy’s®)'
'Watt Café'
'Barnett Hall'
'Benet Hall'
'Bowen Hall'
'Bradley Hall'
'Byrnes Hall'
'Calhoun Courts Apartments'
'Cope Hall'
'Core Campus'
'Donaldson Hall'
'Geer Hall'
'Holmes Hall'
'Johnstone Hall'
'Lever Hall'
'Lightsey Bridge I Apartments'
'Lightsey Bridge II Apartments'
'Manning Hall'
'Mauldin Hall'
'McCabe Hall'
'Norris Hall'
'Sanders Hall'
'Simpson Hall North'
'Simpson Hall South'
'Smith Hall'
'Stadium Suites'
'Thornhill Village Apartments'
'Wannamaker Hall'
'Young Hall'
'Barnes Center'
'Fike Recreation Center'
'Hendrix Student Center'
'Redfern Health Center'
'Union Station'
'University Union, Edgar Brown'
'Botanical Gardens'
'Brooks Center for the Performing Arts'
'Campbell Carriage House Coffee and Gift Shop'
'Campbell Geology Museum'
'Campbell Museum of Natural History'
'Carillon Garden'
'Class of 1957 Rotunda'
'Class of 1960 North Green'
'Clemson, Thomas Green Statue (Gantt Circle)'
'Cox Plaza'
'Fort Hill (Calhoun and Clemson Mansion)'
'Fran Hanson Discovery Center'
'Lee Hall (Lee Art Gallery)'
'Madren Center'
'Martin Inn'
'Military Heritage Plaza'
'Outdoor Theatre (Amphitheater)'
'Reunion Square'
'Scroll of Honor Memorial'
'Visitors Center, Class of 1944'
'Walker Golf Course Clubhouse'
'Woodland Cemeter'
